//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject_1.EmployeeReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeReference.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeesResponse")]
        MyWCFService.EmployeeTBL[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<MyWCFService.EmployeeTBL[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/LoginDetails", ReplyAction="http://tempuri.org/IEmployeeService/LoginDetailsResponse")]
        MyWCFService.UsersTBL LoginDetails(MyWCFService.Models.LoginData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/LoginDetails", ReplyAction="http://tempuri.org/IEmployeeService/LoginDetailsResponse")]
        System.Threading.Tasks.Task<MyWCFService.UsersTBL> LoginDetailsAsync(MyWCFService.Models.LoginData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : SampleProject_1.EmployeeReference.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<SampleProject_1.EmployeeReference.IEmployeeService>, SampleProject_1.EmployeeReference.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyWCFService.EmployeeTBL[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<MyWCFService.EmployeeTBL[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public MyWCFService.UsersTBL LoginDetails(MyWCFService.Models.LoginData data) {
            return base.Channel.LoginDetails(data);
        }
        
        public System.Threading.Tasks.Task<MyWCFService.UsersTBL> LoginDetailsAsync(MyWCFService.Models.LoginData data) {
            return base.Channel.LoginDetailsAsync(data);
        }
    }
}
